environment:
  matrix:
    - LWS_METHOD: x64cl
      CMAKE_ARGS: -DCMAKE_GENERATOR_PLATFORM=x64 -DLWS_WITH_DISTRO_RECOMMENDED=0 -DLWS_WITH_HTTP2=0 -DLWS_WITH_LWSWS=0 -DLWS_WITH_CGI=0 -DLWS_IPV6=0 -DLWS_UNIX_SOCK=0 -DLWS_WITH_PLUGINS=0 -DLWS_WITH_HTTP_PROXY=0 -DLWS_WITH_ZIP_FOPS=0 -DLWS_WITH_SOCKS5=0 -DLWS_WITH_GENERIC_SESSIONS=0 -DLWS_WITH_PEER_LIMITS=0 -DLWS_WITH_ACCESS_LOG=0 -DLWS_WITH_RANGES=0 -DLWS_WITH_SERVER_STATUS=0 -DLWS_WITH_ACME=0 -DLWS_WITH_SSL=1 -DLWS_WITH_MBEDTLS=0 -DLWS_WITH_BORINGSSL=0 -DLWS_WITH_CYASSL=0 -DLWS_WITH_WOLFSSL=0 -DLWS_SSL_CLIENT_USE_OS_CA_CERTS=1 -DLWS_WITH_LIBEV=0 -DLWS_WITH_LIBUV=0 -DLWS_WITH_LIBEVENT=0 -DLWS_WITH_STATIC=1 -DLWS_WITH_SHARED=1 -DLWS_LINK_TESTAPPS_DYNAMIC=0 -DLWS_STATIC_PIC=0 -DLWS_WITH_ESP32=0 -DLWS_PLAT_OPTEE=0 -DLWS_WITHOUT_CLIENT=0 -DLWS_WITHOUT_SERVER=0 -DLWS_WITHOUT_TESTAPPS=0 -DLWS_WITHOUT_TEST_SERVER=0 -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=0 -DLWS_WITHOUT_TEST_PING=0 -DLWS_WITHOUT_TEST_ECHO=0 -DLWS_WITHOUT_TEST_CLIENT=0 -DLWS_WITHOUT_TEST_FRAGGLE=0 -DLWS_WITHOUT_EXTENSIONS=1 -DLWS_WITH_ZLIB=0 -DLWS_WITHOUT_BUILTIN_GETIFADDRS=0 -DLWS_FALLBACK_GETHOSTBYNAME=0 -DLWS_WITHOUT_BUILTIN_SHA1=0 -DLWS_WITH_LATENCY=0 -DLWS_WITHOUT_DAEMONIZE=1 -DLWS_SSL_SERVER_WITH_ECDH_CERT=0 -DLWS_WITH_LEJP=0 -DLWS_WITH_LEJP_CONF=0 -DLWS_WITH_SQLITE3=0 -DLWS_WITH_SMTP=0 -DLWS_WITH_NO_LOGS=0 -DLWS_AVOID_SIGPIPE_IGN=0 -DLWS_WITH_STATS=0 -DLWS_WITH_JWS=0 -DLWS_WITH_GENHASH=0 -DLWS_WITH_GENRSA=0 -DLWS_WITH_SELFTESTS=0 -DLWS_WITH_GCOV=0 -DLWS_WITH_EXPORT_LWSTARGETS=1 -DLWS_REPRODUCIBLE=1

    - LWS_METHOD: default

install:
  - appveyor DownloadFile https://libwebsockets.org:444/win-libuv.zip
  - mkdir c:\assets
  - mkdir c:\assets\libuv
  - 7z x -oc:\assets\libuv win-libuv.zip
  - appveyor DownloadFile https://libwebsockets.org:444/win-libuv64.zip
  - mkdir c:\assets\libuv64
  - 7z x -oc:\assets\libuv64 win-libuv64.zip
  - appveyor DownloadFile https://libwebsockets.org:444/nsis-3.0rc1-setup.exe
  - cmd /c start /wait nsis-3.0rc1-setup.exe /S /D=C:\nsis
  - appveyor DownloadFile https://libwebsockets.org:444/sqlite-dll-win32-x86-3130000.zip
  - mkdir c:\assets\sqlite3
  - 7z x -oc:\assets\sqlite3 sqlite-dll-win32-x86-3130000.zip
  - SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;c:\nsis;%PATH%

build:
  parallel: true
  verbosity: minimal

build_script:
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release %CMAKE_ARGS% ..
  - cmake --build . --config Release

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir staging
  - mkdir staging\include
  - cp -r %APPVEYOR_BUILD_FOLDER%\build\bin %APPVEYOR_BUILD_FOLDER%\build\lib staging
  - if EXIST staging\bin\share mv staging\bin\share staging
  - if NOT EXIST staging\share\libwebsockets-test-server mkdir staging\share\libwebsockets-test-server
  - IF EXIST %APPVEYOR_BUILD_FOLDER%\build\libwebsockets-test-server.pem cp %APPVEYOR_BUILD_FOLDER%\build\libwebsockets-test-server.pem staging\share\libwebsockets-test-server
  - IF EXIST %APPVEYOR_BUILD_FOLDER%\build\libwebsockets-test-server.key.pem cp %APPVEYOR_BUILD_FOLDER%\build\libwebsockets-test-server.key.pem staging\share\libwebsockets-test-server
  - IF EXIST %APPVEYOR_BUILD_FOLDER%\build\lws_config.h cp %APPVEYOR_BUILD_FOLDER%\build\lws_config.h staging\include
  - cp %APPVEYOR_BUILD_FOLDER%\lib\libwebsockets.h staging\include
  - 7z a build\lws-%LWS_METHOD%-%APPVEYOR_BUILD_ID%.zip %APPVEYOR_BUILD_FOLDER%\staging\*

artifacts:
  - path: build\lws-%LWS_METHOD%-%APPVEYOR_BUILD_ID%.zip

deploy:
- provider: BinTray
  username: lws-team
  api_key:
    secure: nDpZ7P/wrk98DwJPMC6KpCC23QrVP8f3RxvKzBaqOmb9LiVrg1IyO1cc5vcgShZC
  subject: lws-team
  repo: libwebsockets
  package: windows
  publish: true
  override: true
  explode: false

matrix:
  fast_finish: true
